apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphiteExporter.fullname" . }}
  labels:
    {{- include "graphiteExporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: prometheus
      port: 9108
      protocol: TCP
      targetPort: prometheus
    - name: graphite
      port: 9109
      protocol: TCP
      targetPort: graphite
    - name: graphite-udp
      port: 9109
      protocol: UDP
      targetPort: graphite-udp
  selector:
    {{- include "graphiteExporter.selectorLabels" . | nindent 4 }}
