dataIngestion:
  espbench:
    enabled: true

bullet:
  enabled: true
  sparkBackend:
    config:
      bullet:
        spark:
          dsl:
            data:
              producer:
                enable: true
            deserializer:
              enable: false
        dsl:
          connector:
            class:
              name: com.yahoo.bullet.dsl.connector.KafkaConnector
            kafka:
              topics:
                - SketchBench-1-1
              bootstrap:
                servers: kafka:9092
          converter:
            class:
              name: com.yahoo.bullet.dsl.converter.JSONBulletRecordConverter
            schema:
              type:
                check:
                  enable: false
          deserializer:
            class:
              name: com.yahoo.bullet.dsl.deserializer.IdentityDeserializer
    dsl:
      schema: |
        {
          "fields": [
            {
              "name": "messageID",
              "type": "INTEGER"
            },
            {
              "name": "ts",
              "type": "STRING"
            },
            {
              "name": "index",
              "type": "LONG"
            },
            {
              "name": "mf01",
              "type": "INTEGER"
            },
            {
              "name": "mf02",
              "type": "INTEGER"
            },
            {
              "name": "mf03",
              "type": "INTEGER"
            },
            {
              "name": "pc13",
              "type": "INTEGER"
            },
            {
              "name": "pc14",
              "type": "INTEGER"
            },
            {
              "name": "pc15",
              "type": "INTEGER"
            },
            {
              "name": "pc25",
              "type": "INTEGER"
            },
            {
              "name": "pc26",
              "type": "INTEGER"
            },
            {
              "name": "pc27",
              "type": "INTEGER"
            },
            {
              "name": "res",
              "type": "INTEGER"
            }
          ]
        }
