runMode: local
interpreters:
  - file
  - spark
  - md
  - python
  - livy
  - sparql
sparkInterpreter:
  spark:
    master: "spark://spark-master-svc:7077"
    submit:
      deployMode: "client"
    app:
      name: "zeppelin"
