dataIngestion:
  nexmark:
    enabled: true

zeppelin:
  enabled: true
  runMode: local
  interpreters:
    - file
    - spark
    - md
    - python
    - livy
    - sparql
  sparkInterpreter:
    spark:
      master: "spark://my-sketchbench-spark-master-svc:7077"
      submit:
        deployMode: "client"
      app:
        name: "zeppelin"

spark:
  enabled: true
  image:
    repository: sketchbench/bullet-spark-3.0
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  worker:
    replicaCount: 3
    coreLimit: 3

bullet:
  enabled: true
  spark:
    enabled: false
  sparkBackend:
    image:
      repository: sketchbench/bullet-spark-3.0
    config:
      bullet:
        spark:
          dsl:
            data:
              producer:
                enable: true
            deserializer:
              enable: false
        dsl:
          connector:
            class:
              name: com.yahoo.bullet.dsl.connector.KafkaConnector
            kafka:
              topics:
                - SketchBench-1-1
              bootstrap:
                servers:
                  - kafka:9092
          converter:
            class:
              name: com.yahoo.bullet.dsl.converter.JSONBulletRecordConverter
            schema:
              type:
                check:
                  enable: false
          deserializer:
            class:
              name: com.yahoo.bullet.dsl.deserializer.IdentityDeserializer
    dsl:
      schema: |
        {
          "fields": [
            {
              "name": "iij_timestamp",
              "type": "LONG"
            },
            {
              "name": "auction_id",
              "type": "INTEGER"
            },
            {
              "name": "partition_id",
              "type": "INTEGER"
            },
            {
              "name": "time",
              "type": "LONG"
            },
            {
              "name": "person",
              "type": "INTEGER"
            },
            {
              "name": "bid",
              "type": "INTEGER"
            }
          ]
        }
