dataIngestion:
  nexmark:
    enabled: true

zeppelin:
  enabled: true
  runMode: local
  interpreters:
    - file
    - spark
    - md
    - python
    - livy
    - sparql
  sparkInterpreter:
    spark:
      master: "spark://my-sketchbench-spark-master-svc:7077"
      submit:
        deployMode: "client"
      app:
        name: "zeppelin"
      jar:
        packages: org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.2,org.apache.spark:spark-streaming-kafka-0-10-assembly_2.12:3.0.2

spark:
  enabled: true
  image:
    repository: sketchbench/bullet-spark-3.0
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  worker:
    replicaCount: 3
    coreLimit: 3

kafdrop:
  enabled: true
