kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "zeppelin.fullname" . }}-config
data:
  log4j.properties: |-
    log4j.rootLogger = INFO, stdout
    log4j.appender.stdout = org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.Threshold = {{ .Values.logLevel }}
    log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%5p [%d] ({%t} %F[%M]:%L) - %m%n
    log4j.logger.org.apache.zeppelin.interpreter = {{ .Values.logLevel }}
