apiVersion: v2
name: sketchbench
description: A benchmark suite for stochastic streaming algorithms
type: application
version: 0.1.2
appVersion: "1.0.0"
home: https://spark.apache.org/
# icon:
maintainers:
  - name: FraBle
    email: frankb2@illinois.edu
    url: https://github.com/FraBle
  - name: makamhareesh
    email: hmakam2@illinois.edu
    url: https://github.com/makamhareesh
  - name: mukrpe
    email: mkp5@illinois.edu
    url: https://github.com/mukrpe
sources:
  - https://github.com/SketchBench/charts
annotations:
  artifacthub.io/signKey: |
    fingerprint: F6F77B76587337D518F42D9CE720A2903AF94931
    url: https://keybase.io/frable90/pgp_keys.asc
keywords:
  - apache
  - bullet
  - spark
  - storm
  - kafka
  - sketch
  - benchmark
dependencies:
  - name: bullet
    version: 0.2.0
    repository: https://sketchbench.github.io/bullet-k8s
    condition: bullet.enabled
  - name: kafka
    version: 13.0.2
    repository: https://charts.bitnami.com/bitnami
    import-values:
      - child: service
        parent: dataIngestion.kafka
      - child: zookeeper.service
        parent: dataIngestion.zookeeper
  - name: kafdrop
    version: 0.2.3
    repository: https://bedag.github.io/helm-charts
    condition: kafdrop.enabled
  - name: spark
    version: 5.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: spark.enabled
    import-values:
      - child: master
        parent: bullet.sparkBackend.cluster
  - name: tobs
    version: 0.5.0
    repository: https://charts.timescale.com
    condition: tobs.enabled
  - name: zeppelin
    version: 0.1.0
    repository: https://sketchbench.github.io/charts
    condition: zeppelin.enabled
