apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sketchbench.fullname" . }}-data-ingestion-nexmark
  labels:
    {{- include "sketchbench.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-ingestion-nexmark
